### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by falconmick** [falconmick/blog#27]
# 1.0.0
- [ ] Seo check
- [ ] Test all old URL redirect to new
- [ ] Sitemap 
- [ ] Write welcome to new blog post

# 2.0.0
- [ ] Comments
- [ ] Re-write layout in style components
